function auxFile = model2auxiliary(modelFile, auxFile, convention)
%MODEL2AUXILIARY  Build the variational ("sensitivity") augmentation of
%   an IQMtools-style model_*.txt file; function generated by Claude AI.
%
%   auxFile = MODEL2AUXILIARY(modelFile) reads modelFile (e.g.
%   'model_GLV.txt') and writes 'auxiliary_GLV.txt' in the same folder.
%   The output contains the original states, unchanged, plus the n^2
%   entries of a matrix Phi, Phi(0) = I_n, computed in one of two ways
%   (see the CONVENTION argument below).
%
%   auxFile = MODEL2AUXILIARY(modelFile, auxFile) lets you choose the
%   output file path explicitly. Pass [] to keep the default name.
%
%   auxFile = MODEL2AUXILIARY(modelFile, auxFile, convention) selects
%   which Phi equations to generate:
%
%     'standard' (default) -- the classical state-transition /
%         fundamental-matrix ODE
%             dPhi/dt = J(x) * Phi ,     Phi(0) = I_n
%         with dx/dt = f(x) the original system and J(x) = df/dx its
%         Jacobian, evaluated along the literal, shared state
%         trajectory x(t). This is what auxiliary_GLV.txt and
%         auxiliary_linear_oscillator.txt use.
%
%     'legacy' -- the convention actually used in auxiliary_HS.txt,
%         auxiliary_STAT5.txt, auxiliary_TCS.txt and auxiliary_
%         repressilator.txt. There each column j of Phi is its own,
%         self-contained nonlinear ODE
%             dPhi(:,j)/dt = J( Phi(:,j) ) * Phi(:,j) ,  Phi(:,j)(0) = e_j
%         i.e. the Jacobian for column j is evaluated with the state
%         vector x replaced by that column's own current value,
%         instead of the real trajectory -- so every column uses a
%         *different* Jacobian, and the true state trajectory x(t)
%         never enters the Phi equations at all. Mathematically this
%         is not the standard sensitivity/fundamental-matrix equation,
%         but it is exactly, verifiably (checked symbolically against
%         all four files, entry by entry) what those four files
%         contain, so it's offered here as an explicit option.
%
%   Both conventions coincide whenever J(x) does not actually depend
%   on the states (e.g. auxiliary_linear_oscillator.txt, and the
%   state-independent rows of auxiliary_STAT5.txt) since there's then
%   nothing to substitute.
%
%   Every other section (MODEL NAME, NOTES, PARAMETERS, VARIABLES,
%   REACTIONS, FUNCTIONS, EVENTS, MATLAB FUNCTIONS) is copied through
%   unchanged regardless of convention. Calls to functions defined in
%   MODEL FUNCTIONS (e.g. input(time), as in the STAT5 model) are
%   treated as opaque terms: since they do not depend on the states,
%   their contribution to the Jacobian is automatically zero, and they
%   are carried through to the output unchanged. Simple algebraic
%   aliases defined in MODEL VARIABLES (none of the shipped example
%   models use this section) are inlined before differentiation on a
%   best-effort basis.
%
%   Requires the Symbolic Math Toolbox.
%
%   The two conventions are only distinguished by their content, not by
%   the output filename, so pass AUXFILE explicitly if you want to keep
%   both versions for the same model (they'd otherwise both default to
%   the same 'auxiliary_<name>.txt' and the second call would overwrite
%   the first).
%
%   Example:
%       model2auxiliary('model_GLV.txt');                     % standard
%       model2auxiliary('model_GLV.txt', ...
%           'auxiliary_GLV_legacy.txt', 'legacy');            % legacy
%
%       d = dir('model_*.txt');
%       for k = 1:numel(d)
%           model2auxiliary(fullfile(d(k).folder, d(k).name));
%       end

    if nargin < 2 || isempty(auxFile)
        auxFile = defaultAuxName(modelFile);
    end
    if nargin < 3 || isempty(convention)
        convention = 'standard';
    end
    convention = validatestring(convention, {'standard', 'legacy'});

    raw = fileread(modelFile);
    raw = regexprep(raw, '\r\n', '\n');
    raw = regexprep(raw, '\r', '\n');

    [sections, order] = splitSections(raw);

    if ~isfield(sections, 'STATES')
        error('model2auxiliary:noStates', ...
            'No "MODEL STATES" section found in %s.', modelFile);
    end

    [stateNames, rhsMap, icMap] = parseStates(sections.STATES);
    n = numel(stateNames);
    if n == 0
        error('model2auxiliary:noStates', ...
            'Could not parse any d/dt(...) equations from %s.', modelFile);
    end

    stateRHS = cellfun(@(nm) rhsMap(nm), stateNames, 'UniformOutput', false);
    stateIC  = cell(1, n);
    for k = 1:n
        if isKey(icMap, stateNames{k})
            stateIC{k} = icMap(stateNames{k});
        else
            warning('model2auxiliary:noIC', ...
                'No initial condition found for state %s; defaulting to 0.', stateNames{k});
            stateIC{k} = '0';
        end
    end

    paramNames = {};
    if isfield(sections, 'PARAMETERS')
        paramNames = parseNames(sections.PARAMETERS);
    end

    reserved = intersect([stateNames(:); paramNames(:)]', {'i', 'j'});
    if ~isempty(reserved)
        error('model2auxiliary:reservedName', ...
            ['State/parameter name(s) %s clash with the symbolic ' ...
             'imaginary unit in MATLAB; please rename them before ' ...
             'converting.'], strjoin(reserved, ', '));
    end

    funcDefs = struct('name', {}, 'args', {});
    if isfield(sections, 'FUNCTIONS')
        funcDefs = parseFunctionHeaders(sections.FUNCTIONS);
    end
    if isempty(funcDefs)
        funcNames = {};
    else
        funcNames = {funcDefs.name};
    end

    varDefs = struct('name', {}, 'expr', {});
    if isfield(sections, 'VARIABLES')
        varDefs = parseVariableDefs(sections.VARIABLES);
    end

    % ---- protect opaque function calls (e.g. input(time)) -------------
    if isempty(varDefs)
        toProtect = stateRHS;
    else
        toProtect = [stateRHS, {varDefs.expr}];
    end
    [protectedAll, placeholders] = protectFunctionCalls(toProtect, funcNames);
    stateRHSProtected = protectedAll(1:n);
    for k = 1:numel(varDefs)
        varDefs(k).expr = protectedAll{n + k};
    end

    % ---- inline MODEL VARIABLES aliases (best effort) ------------------
    stateRHSProtected = inlineVariables(stateRHSProtected, varDefs);

    % ---- symbolic states and right-hand side ----------------------------
    x = sym(stateNames(:));
    f = sym(zeros(n, 1));
    for k = 1:n
        f(k) = str2sym(stateRHSProtected{k});
    end

    % ---- Jacobian and the Phi ODE ----------------------------------------
    J = jacobian(f, x);

    width = 1;
    if n >= 10
        width = numel(num2str(n));
    end
    phName = @(i, j) sprintf('Ph%0*d%0*d', width, i, width, j);

    Phi = sym(zeros(n, n));
    for j = 1:n
        for i = 1:n
            Phi(i, j) = str2sym(phName(i, j));
        end
    end

    switch convention
        case 'standard'
            % dPhi/dt = J(x) * Phi, x the shared, literal state trajectory.
            dPhi = J * Phi;
        case 'legacy'
            % Each column j gets its own Jacobian, evaluated with the
            % state vector replaced by that column's own Phi values.
            dPhi = sym(zeros(n, n));
            for j = 1:n
                colj = Phi(:, j);
                Jj = subs(J, x, colj);
                dPhi(:, j) = Jj * colj;
            end
    end

    % ---- render the Phi equations, restoring protected function calls --
    phiLines = {};
    for j = 1:n
        for i = 1:n
            s = char(dPhi(i, j));
            s = restoreFunctionCalls(s, placeholders);
            phiLines{end+1} = sprintf('d/dt(%s) = %s', phName(i, j), s); %#ok<AGROW>
        end
        phiLines{end+1} = ''; %#ok<AGROW>
    end
    if ~isempty(phiLines) && isempty(phiLines{end})
        phiLines(end) = [];
    end

    % ---- original state equations, verbatim -----------------------------
    stateLines = cell(1, n);
    for k = 1:n
        stateLines{k} = sprintf('d/dt(%s) = %s', stateNames{k}, stateRHS{k});
    end

    % ---- initial conditions ----------------------------------------------
    icLines = cell(1, n);
    for k = 1:n
        icLines{k} = sprintf('%s(0) = %s', stateNames{k}, stateIC{k});
    end

    phiIcLines = {};
    for j = 1:n
        for i = 1:n
            phiIcLines{end+1} = sprintf('%s(0) = %d', phName(i, j), double(i == j)); %#ok<AGROW>
        end
        phiIcLines{end+1} = ''; %#ok<AGROW>
    end
    if ~isempty(phiIcLines) && isempty(phiIcLines{end})
        phiIcLines(end) = [];
    end

    newStates = strjoin([stateLines, {''}, phiLines, {''}, icLines, {''}, phiIcLines], sprintf('\n'));
    sections.STATES = newStates;

    % ---- write the augmented model out -------------------------------------
    writeModelFile(auxFile, sections, order);
end

% ========================================================================
% Local helper functions
% ========================================================================

function outFile = defaultAuxName(modelFile)
    [p, nm, ext] = fileparts(modelFile);
    if startsWith(nm, 'model_')
        nm = ['auxiliary_' nm(numel('model_')+1:end)];
    else
        nm = ['auxiliary_' nm];
    end
    if isempty(ext)
        ext = '.txt';
    end
    if isempty(p)
        outFile = [nm ext];
    else
        outFile = fullfile(p, [nm ext]);
    end
end

function [sections, order] = splitSections(txt)
    lines = strsplit(txt, sprintf('\n'), 'CollapseDelimiters', false);
    sections = struct();
    order = {};
    curField = '';
    buf = {};
    for k = 1:numel(lines)
        ln = lines{k};
        tok = regexp(ln, '^\*{5,}\s*(.*)$', 'tokens', 'once');
        if ~isempty(tok)
            if ~isempty(curField)
                sections.(curField) = strjoin(buf, sprintf('\n'));
            end
            title = strtrim(tok{1});
            fname = regexprep(upper(title), '^MODEL\s+', '');
            fname = regexprep(fname, '\s+', '');
            if isempty(fname)
                fname = 'UNKNOWN';
            end
            curField = fname;
            order{end+1} = curField; %#ok<AGROW>
            buf = {};
        else
            if ~isempty(curField)
                buf{end+1} = ln; %#ok<AGROW>
            end
        end
    end
    if ~isempty(curField)
        sections.(curField) = strjoin(buf, sprintf('\n'));
    end
end

function stmts = joinLogicalLines(sectionText)
%JOINLOGICALLINES  Join lines whose parentheses are unbalanced with the
%   following line(s), so that a statement split across several
%   physical lines (e.g. the interp1IQM(...) call in the STAT5 model)
%   is treated as one logical statement. Blank lines separate
%   statements when parentheses are balanced.
    lines = strsplit(sectionText, sprintf('\n'), 'CollapseDelimiters', false);
    stmts = {};
    buf = '';
    depth = 0;
    for k = 1:numel(lines)
        ln = lines{k};
        if depth == 0 && isempty(strtrim(ln))
            if ~isempty(strtrim(buf))
                stmts{end+1} = strtrim(buf); %#ok<AGROW>
            end
            buf = '';
            continue
        end
        if isempty(buf)
            buf = ln;
        else
            buf = [buf ' ' strtrim(ln)]; %#ok<AGROW>
        end
        depth = depth + numel(strfind(ln, '(')) - numel(strfind(ln, ')'));
        if depth <= 0
            stmts{end+1} = strtrim(buf); %#ok<AGROW>
            buf = '';
            depth = 0;
        end
    end
    if ~isempty(strtrim(buf))
        stmts{end+1} = strtrim(buf);
    end
end

function [names, rhsMap, icMap] = parseStates(sectionText)
    stmts = joinLogicalLines(sectionText);
    names = {};
    rhsMap = containers.Map('KeyType', 'char', 'ValueType', 'char');
    icMap  = containers.Map('KeyType', 'char', 'ValueType', 'char');
    odePat = '^d/dt\(\s*([A-Za-z_]\w*)\s*\)\s*=\s*(.+)$';
    icPat  = '^([A-Za-z_]\w*)\s*\(\s*0\s*\)\s*=\s*(.+)$';
    for k = 1:numel(stmts)
        tok = regexp(stmts{k}, odePat, 'tokens', 'once');
        if ~isempty(tok)
            nm = tok{1};
            if ~isKey(rhsMap, nm)
                names{end+1} = nm; %#ok<AGROW>
            end
            rhsMap(nm) = strtrim(tok{2}); %#ok<NASGU>
            continue
        end
        tok = regexp(stmts{k}, icPat, 'tokens', 'once');
        if ~isempty(tok)
            icMap(tok{1}) = strtrim(tok{2}); %#ok<NASGU>
        end
    end
end

function names = parseNames(sectionText)
    stmts = joinLogicalLines(sectionText);
    names = {};
    for k = 1:numel(stmts)
        tok = regexp(stmts{k}, '^([A-Za-z_]\w*)\s*=', 'tokens', 'once');
        if ~isempty(tok)
            names{end+1} = tok{1}; %#ok<AGROW>
        end
    end
end

function defs = parseFunctionHeaders(sectionText)
    stmts = joinLogicalLines(sectionText);
    defs = struct('name', {}, 'args', {});
    for k = 1:numel(stmts)
        tok = regexp(stmts{k}, '^([A-Za-z_]\w*)\s*\(([^)]*)\)\s*=', 'tokens', 'once');
        if ~isempty(tok)
            idx = numel(defs) + 1;
            defs(idx).name = tok{1};
            argsRaw = strtrim(tok{2});
            if isempty(argsRaw)
                defs(idx).args = {};
            else
                defs(idx).args = strtrim(strsplit(argsRaw, ','));
            end
        end
    end
end

function defs = parseVariableDefs(sectionText)
    stmts = joinLogicalLines(sectionText);
    defs = struct('name', {}, 'expr', {});
    for k = 1:numel(stmts)
        tok = regexp(stmts{k}, '^([A-Za-z_]\w*)\s*=\s*(.+)$', 'tokens', 'once');
        if ~isempty(tok)
            idx = numel(defs) + 1;
            defs(idx).name = tok{1};
            defs(idx).expr = strtrim(tok{2});
        end
    end
end

function [outExprs, placeholders] = protectFunctionCalls(exprs, funcNames)
%PROTECTFUNCTIONCALLS  Replace calls to user-defined MODEL FUNCTIONS
%   (e.g. input(time)) with opaque placeholder symbols so symbolic
%   differentiation treats them as constants w.r.t. the state vector.
%   Their original text is restored afterwards with RESTOREFUNCTIONCALLS.
    placeholders = containers.Map('KeyType', 'char', 'ValueType', 'char');
    outExprs = exprs;
    if isempty(funcNames)
        return
    end
    counter = 0;
    for k = 1:numel(outExprs)
        s = outExprs{k};
        for fIdx = 1:numel(funcNames)
            [s, counter, placeholders] = replaceCalls(s, funcNames{fIdx}, counter, placeholders);
        end
        outExprs{k} = s;
    end
end

function [s, counter, placeholders] = replaceCalls(s, fname, counter, placeholders)
    pat = ['(?<![A-Za-z0-9_])' regexptranslate('escape', fname) '\s*\('];
    while true
        [startIdx, endIdx] = regexp(s, pat, 'start', 'end', 'once');
        if isempty(startIdx)
            break
        end
        openIdx = endIdx; % index of the matched '(' character
        depth = 1;
        closeIdx = 0;
        for c = (openIdx + 1):length(s)
            if s(c) == '('
                depth = depth + 1;
            elseif s(c) == ')'
                depth = depth - 1;
                if depth == 0
                    closeIdx = c;
                    break
                end
            end
        end
        if closeIdx == 0
            break % unbalanced parentheses; leave the rest untouched
        end
        fullCall = s(startIdx:closeIdx);
        counter = counter + 1;
        token = sprintf('internalFn%dq', counter);
        placeholders(token) = fullCall; %#ok<NASGU>
        s = [s(1:startIdx-1) token s(closeIdx+1:end)];
    end
end

function exprs = inlineVariables(exprs, varDefs)
%INLINEVARIABLES  Best-effort textual inlining of MODEL VARIABLES
%   aliases into the (already function-call-protected) state RHS
%   expressions, resolving simple chains of variable references.
    if isempty(varDefs)
        return
    end
    for pass = 1:5
        changed = false;
        for k = 1:numel(exprs)
            for v = 1:numel(varDefs)
                pat = ['(?<![A-Za-z0-9_])' regexptranslate('escape', varDefs(v).name) '(?![A-Za-z0-9_])'];
                if ~isempty(regexp(exprs{k}, pat, 'once'))
                    exprs{k} = regexprep(exprs{k}, pat, ['(' varDefs(v).expr ')']);
                    changed = true;
                end
            end
        end
        if ~changed
            break
        end
    end
end

function s = restoreFunctionCalls(s, placeholders)
    ks = keys(placeholders);
    for k = 1:numel(ks)
        tok = ks{k};
        s = strrep(s, tok, placeholders(tok));
    end
end

function writeModelFile(fname, sections, order)
    titleMap = containers.Map( ...
        {'NAME', 'NOTES', 'STATES', 'PARAMETERS', 'VARIABLES', 'REACTIONS', ...
         'FUNCTIONS', 'EVENTS', 'MATLABFUNCTIONS'}, ...
        {'MODEL NAME', 'MODEL NOTES', 'MODEL STATES', 'MODEL PARAMETERS', ...
         'MODEL VARIABLES', 'MODEL REACTIONS', 'MODEL FUNCTIONS', ...
         'MODEL EVENTS', 'MODEL MATLAB FUNCTIONS'});
    fid = fopen(fname, 'w');
    if fid < 0
        error('model2auxiliary:cannotWrite', 'Could not open %s for writing.', fname);
    end
    cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>
    for k = 1:numel(order)
        key = order{k};
        if isKey(titleMap, key)
            title = titleMap(key);
        else
            title = key;
        end
        fprintf(fid, '********** %s\n', title);
        if isfield(sections, key)
            fprintf(fid, '%s\n', sections.(key));
        end
        fprintf(fid, '\n');
    end
end
